baseURL: "https://afnanabdul.dev/" 
title: Afn치n Alabdulwahab
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Blog
          url: blog/
          weight: 4
        # - name: Tags
        #   url: tags/
        #   weight: 5

params:
    description: "I am a software engineer & data science garduate student at the University of Virginia."
    author: Afn치n Alabdulwahab
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about", "projects", "courses", "blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Afn치n Alabdulwahab
          subtitle: "I'm a software engineer looking to transition into a research role in AI. My undergraduate education was in Electrical and Computer Engineering, and after working five years as a software engineer in industrial automation, I recently earned my master's in Data Science from the University of Virginia.

          <br><br>
          I am mostly interested in AI research and development across two key areas: AI safety and AI systems optimization. In AI safety, I'm particularly interested in mechanistic interpretability and model evaluation, drawn to understanding the internal mechanisms that drive AI behavior. In AI systems, I'm interested in compiler design, programming language theory, and how language design principles and abstractions can enable more efficient and reliable AI workloads.
          <br><br>
          This is where I showcase my projects and share thoughts on topics I'm exploring.
          "
          imageUrl: "prof_pic.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            # Commenting out buttons while working on content (About, Projects and Blog)
            - name: About
              url: about/
            - name: Projects
              url: projects/
            - name: Courses
              url: courses/
            - name: Blog
              url: blog/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: "/cv.pdf"
        - name: Email
          url: mailto:hi@afnanabdul.dev
        - name: GitHub
          url: https://github.com/afnanabdul
        - name: LinkedIn
          url: https://www.linkedin.com/in/afnan-alabdulwahab
        # - name: Location
        #   url: location/
#        - name: Zoom
#          url: https://www.zoom.us/my/igelfeld
#        - name: Office Hours
#          url: officehours/
#        - name: Google Scholar
#          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
#        - name: Substack
#          url: https://pmichaillat.substack.com
#        - name: YouTube
#          url: https://www.youtube.com/@alexandermccallsmithoffici9000
#        - name: Twitter
#          url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
        customCSS: ["css/extended/custom.css"]
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Afn치n"
      icon: apple-touch-icon.png
      iconHeight: 64

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2